name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  piper-command:  # id of input
    description: 'Piper comand'
    required: true
    default: 'version'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'