name: Trigger Integration Tests

on:
  issue_comment:
    types: [created]

jobs:
  build: 
    name: Trigger Integration Tests
    
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/it' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER')
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: change branch
        run: git fetch origin +refs/pull/$PR/merge && git checkout FETCH_HEAD
      - name: push it branch
        run: git push origin it/1
      
  
