name: Trigger Integration Tests

on:
  issue_comment:
    types: [created]

jobs:
  build:
    name: Trigger Integration Tests
    
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/it' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER')
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          branch: origin/pr/1
      - name: push it branch
        run: git status
      - name: git checkout
        run: cat "$GITHUB_EVENT_PATH"
      
  
