name: Trigger Integration Tests

on:
  issue_comment:
    types: [created]

jobs:
  build:
    name: Trigger Integration Tests
    
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/it' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER')
    
    steps:
      - name: printenv
        run: echo $GITHUB_EVENT_PATH
      - name: checkout
        uses: actions/checkout@v2
      - name: push it branch
        run: git status
      - name: push it branch
        run: echo $GITHUB_EVENT_PATH
      
  
