name: Trigger Integration Tests

on:
  issue_comment:
    types: [created]

jobs:
  build: 
    name: Trigger Integration Tests
    
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/it' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER')
    
    steps:
      - name: get pull request url
        id: pullrequest
        run: echo "::set-output name=pullrequest::$(curl ${{ github.event.comment.issue_url }} | jq '.pull_request.url' | sed 's/\"//g')"
      - name: pull request details
        id: pullrequestdetails
        run: echo "::set-output name=pullrequestdetails::$(curl ${{ steps.pullrequest.outputs.pullrequest }})"
      - name: get branch name
        id: branchname
        run: echo "::set-output name=branchname::$(echo ${{ steps.pullrequestdetails.outputs.pullrequestdetails }} | jq '.head.ref' | sed 's/\"//g')"
      - name: get repository
        id: repository
        run: echo "::set-output name=repository::$(echo ${{ steps.pullrequestdetails.outputs.pullrequestdetails }} | jq '.head.repo.full_name' | sed 's/\"//g')"
      - name: pull request number
        id: prnumber
        run: echo "::set-output name=prnumber::$(echo ${{ steps.pullrequestdetails.outputs.pullrequestdetails }} | jq '.number' | sed 's/\"//g')"
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.repository.outputs.repository }}
          ref: ${{ steps.branchname.outputs.branchname }}
#       - name: change branch
#         run: git checkout -b it/${{ steps.prnumber.outputs.prnumber }}
#       - name: push it branch
#         run: git push origin it/${{ steps.prnumber.outputs.prnumber }}
      
  
